import Head from 'next/head'
import Image from 'next/image'
import { Hero, Navbar, PayBy, Pricing, Services } from '../components'
import HomeLayout from '../components/Layouts/HomeLayout'
import PaymentBy from '../components/PayBy'
import PaymentSection from '../components/PaymentSection'
import AOS from 'aos';
import "aos/dist/aos.css";
import { useEffect } from 'react'

export default function Home() {

useEffect(()=>{
  AOS.init()
  AOS.refresh({
    duration:500
  })
})

  return (
    <div className=' font-openSans mx-auto w-full'>
      <Head>
        <title>PayMe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<HomeLayout>
  <div className='w-full '>

  <Hero/>
  {/* <PayBy/> */}
  <PaymentSection/>
  <Services/>
  <Pricing/>
  </div>
</HomeLayout>

     
    </div>
  )
}
